services:
  go-app:
    container_name: go-app
    build: ./go-app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8080:8080"
    networks:
      - isrpo-sandbox

  victoria-metrics:
    image: victoriametrics/victoria-metrics
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    command:
      - '-storageDataPath=/victoria-metrics-data'
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
    networks:
      - isrpo-sandbox
    
  vmagent:
    image: victoriametrics/vmagent
    container_name: vmagent
    ports:
      - "8429:8429"
    depends_on:
      - victoria-metrics
    command:
      - '-promscrape.config=/etc/vmagent/prometheus.yml'
      - '-remoteWrite.url=http://victoria-metrics:8428/api/v1/write'
    volumes:
      - ./vmagent/prometheus.yml:/etc/vmagent/prometheus.yml
    networks: 
      - isrpo-sandbox

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./logs/loki-config.yaml:/etc/loki/loki-config.yaml
    networks: 
      - isrpo-sandbox

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./logs/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks: 
      - isrpo-sandbox

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - victoria-metrics
    networks:
      - isrpo-sandbox

networks:
  isrpo-sandbox:
    driver: bridge

volumes:
  victoria-metrics-data:
