services:
  go-app:
    build: path/go-app
    ports:
      - "8080:8080"
    networks:
      - isrpo-sandbox

  victoria-metrics:
    image: victoriametrics/victoria-metrics
    ports:
      - "8428:8428"
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
    networks:
      - isrpo-sandbox
    command:
      - '--storageDataPath=/victoria-metrics-data'
    
    vmagent:
      image: victoriametrics/vmagent
      ports:
        - "8429:8429"
      depends_on:
        - victoria-metrics
      networks:
        - isrpo-sandbox
      volumes:
        - ./config/vmagent.yml:/config/vmagent.yml
      command:
        - '-remoteWrite.url=http://victoria-metrics:8428/api/v1/write'
        - '-scrapeConfig.file=/config/vmagent.yml'

    grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      depends_on:
        - victoria-metrics
      networks:
        - isrpo-sandbox

networks:
  isrpo-sandbox:
    driver: bridge

volumes:
  victoria-metrics-data:
