/*
 * Дендрарий
 *
 * Учет деревьев, кустарников, лиан
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	"github.com/Hodache/isrpo-sandbox/go/middleware"
	"github.com/prometheus/client_golang/prometheus/promhttp"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/Hodache/isrpo-sandbox/go"
)

func main() {
	log.Printf("Server started")
	router := sw.NewRouter()

	// Метрики
	router.Use(middleware.MetricsMiddleware)
	http.Handle("/metrics", promhttp.Handler())

	log.Fatal(http.ListenAndServe(":8080", router))
}
