/*
 * Дендрарий
 *
 * Учет деревьев, кустарников, лиан
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"CreatePlant",
		strings.ToUpper("Post"),
		"/plants",
		CreatePlant,
	},

	Route{
		"DeletePlant",
		strings.ToUpper("Delete"),
		"/plants/{id}",
		DeletePlant,
	},

	Route{
		"GetPlantById",
		strings.ToUpper("Get"),
		"/plants/{id}",
		GetPlantById,
	},

	Route{
		"GetPlants",
		strings.ToUpper("Get"),
		"/plants",
		GetPlants,
	},

	Route{
		"UpdatePlant",
		strings.ToUpper("Put"),
		"/plants/{id}",
		UpdatePlant,
	},

	Route{
		"CollectMetrics",
		strings.ToUpper("Get"),
		"/metrics",
		promhttp.Handler().ServeHTTP,
	},
}
